- name: feature
  description: New feature
  color: 2ba48a

- name: enhancement
  description: Extend feature
  color: 449c0c

- name: bug
  description: Something isn't working
  color: fe4c5e

- name: refactor
  description: Refactoring codes
  color: f27142

- name: dependencies
  description: "Dependency update"
  color: c79b2d

- name: major
  description: Major update
  color: 095ed3

- name: minor
  description: Minor update
  color: 3c83da

- name: ignore
  decription: Won't be written in changelog
  color: 98948e
